lint file add
obed300/MyPortfolio1 pull request #1
Opened 2022-09-22 13:42 UTC by obed300

Using Linters to check errors

2022-09-23 23:26 UTC, Tadesse-Alemayehu reviewed
Hi @obed300  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑🛑

![giphy](https://user-images.githubusercontent.com/69077061/192067778-2983f2e8-68d7-406f-b2c1-6aaad569ab62.gif)

- You have submitted a project, that has no linter setup. Please make sure to set up linter and all check are passing before requesting for the next review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-09-24 01:57 UTC, alexpuente0 requested changes
Hi @obed300 , 

You've done a great job so far!

In this case, however, there are still some issues that you need to work on to finish this project and advance to the next one, but you are almost there!

## Highlights
- No linter errors ✔️ 
- Great use of `div` tags for styling ✔️ 

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 01:57 UTC, alexpuente0 commented on index.html
> +        </div>
- [ ] You can try and wrap this part of the code inside a `section` tag, to maximize code readability

2022-09-24 01:57 UTC, alexpuente0 commented on index.html
> +        </div>
- [ ] You seem to be missing a couple of icons (Angelist and Medium). Also, the order is a bit skewed. Please try to match the design as close as possible, including size, spacing and color of the icons.

2022-09-24 01:57 UTC, alexpuente0 commented on index.html
> +        <header class="header-section">
- [ ] You have wrapped all of your code inside this `div`, which is giving an extra margin at the top. Please try and remove this `div` and make sure that the margins and spacings are matching the desin.
Your design:
![image](https://user-images.githubusercontent.com/99830261/192074549-5c5fd308-8d98-4091-88fb-a10c5e8c6f63.png)
Figma template:
![image](https://user-images.githubusercontent.com/99830261/192074574-74d56d36-1d99-4094-9dcf-1dcec9068065.png)

2022-09-24 01:57 UTC, alexpuente0 commented on style.css
> +}
- [ ] You seem to be missing some of the background elements. Please make sure that you use the images provided on the Figma template, and that they are visible as per the design.

2022-09-24 01:57 UTC, alexpuente0 commented on index.html
> +            </a>
- [ ] This images are supposed to be from the background, but here you are adding them as links (by using the anchor `a` tag). You could try to add this decorative images as a background by using css.

2022-09-24 01:57 UTC, alexpuente0 commented on style.css
> +}
- [ ] Please make sure that the information and properties of the text match the design
Your design:
![image](https://user-images.githubusercontent.com/99830261/192075119-2061feeb-d563-446e-8604-aac006fcd794.png)
Template:
![image](https://user-images.githubusercontent.com/99830261/192075134-f9bca1fd-ea92-4e59-a5a3-011b3f8632cd.png)

2022-09-26 19:24 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @obed300 👋 
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  

<img src="https://media0.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

## Highlights:  
* All tests passed ✔️

## Required Changes:
_Kindly check the comments below_

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-26 19:24 UTC, ha-manel commented on index.html
> +                </a>
- [ ] Kindly wrap this menu button in a `nav` tag for semantic reasons 👍

2022-09-26 19:24 UTC, ha-manel commented on index.html
> +            <div class="headline">
- [ ] Kindly replace this `div` tag with `section` tag for semantic reasons.

2022-09-26 19:24 UTC, ha-manel commented on index.html
> +                               <P class="item">I’m Obed Glad to see you!</P>
- [ ] Kindly replace this `p` tag with `h1` tag. Since this is the main header of the page, it will be semantically correct 💯

2022-09-26 19:24 UTC, ha-manel commented on index.html
> +                </div>
- [ ] Kindly implement the following structure for the social media icons:
  - The wrapper should be a list `ul` instead of `div`.
  - Each icon is an anchor tag `a` (you can add your social links through `href`).
  - Each anchor tag `a` is wrapped in a list item element `li`.
  - The final outcome should be something like:
```
<ul>
  <li><a href="#">icon</a></li>
  <li><a href="#">icon</a></li>
</ul>
```

2022-09-26 19:24 UTC, ha-manel commented on index.html
> +                </div>
- [ ] Kindly reduce the space between the header and the paragraph to match the design on Figma 💯 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/192362070-ca5191af-1b4d-426f-8121-f9371286c750.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/192362101-2c72111a-d652-42a4-9e49-3d1b715b4661.png)

2022-09-26 19:24 UTC, ha-manel commented on index.html
> +                </a>
- [ ] Kindly update the spaces around the header to make it match Figma (I think `margin-right` or `padding-right` needed here)

## Your design:
![image](https://user-images.githubusercontent.com/50721479/192362306-19f2a452-7029-4ee0-aa15-1fb44fe5a71c.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/192362339-f80444a1-6ba5-4947-87d0-7101dec4dc7d.png)

2022-09-27 00:08 UTC, ridwanediallo requested changes
# Changes Required ♻️
## Hi @obed300 , 
![AlmostThereReachGIF](https://user-images.githubusercontent.com/55918904/191301799-36d07166-0e35-4582-a231-7a2d780f7783.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linters checks are ok. ✔


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-27 00:08 UTC, ridwanediallo commented on style.css
> +} */
- [ ] Same here and at lines `107`  to `109`, I would recommend you to remove those commented codes on your codebase. Removing all commented code makes your codebase look professional don't forget that, please.

2022-09-27 06:54 UTC, Olamarx approved these changes
Hi @obed300, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good commit messages ✔️
- Good use of Git and GitHub flows ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-27 07:40 UTC, merged