Contact Form Milestone
obed300/MyPortfolio1 pull request #3
Opened 2022-10-05 10:38 UTC by obed300

In this milestone, I added a contact form

2022-10-05 12:56 UTC, roshan-bajgain requested changes
Hi @obed300, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

## Required Changes ♻️
- [ ] You have implemented almost everything for the contact form but you removed the code that you did last week and the previous day. please implement all things that need to be done. See the image below and please do it.
### only design on whole page
![your](https://user-images.githubusercontent.com/81727988/194065407-4af79ac7-2002-481c-8977-f0896839beaa.png)
### Things that need to implement.
![figmaaaaaa](https://user-images.githubusercontent.com/81727988/194065457-11e55b21-4458-4e82-8d6b-3af42904eaf7.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-05 12:56 UTC, roshan-bajgain commented on index.html
> +                    <li>
- [ ] You should collect the data by using the [Formspree service](https://formspree.io/html). please create an account and then use the id that is generated not the `form_id` 😃

2022-10-05 12:56 UTC, roshan-bajgain commented on index.html
> +            </form>
- [ ] You should Implement the button interactions (enable, hover, etc.). Please see the image below for reference
### Figma design
![sssss](https://user-images.githubusercontent.com/81727988/194063697-de59dea3-4acc-4d2b-8f82-eb1e10a5ae47.png)

2022-10-05 12:56 UTC, roshan-bajgain commented on index.html
> +                      </li>
- [ ] I would suggest you please stick as much as possible to the design. please remove the black border and provide padding to the placeholder
### Your design
![Screenshot 2022-10-05 183440](https://user-images.githubusercontent.com/81727988/194064427-a959b018-4114-4866-a84e-bdad20767446.png)
### Fimga design
![figa](https://user-images.githubusercontent.com/81727988/194064486-5a78248a-2efa-4266-b21a-8548aec7b328.png)

2022-10-06 00:51 UTC, Qoosim commented on index.html
> +                      </li>
> * [ ]  I would suggest you please stick as much as possible to the design. please remove the black border and provide padding to the placeholder
> 
> ### Your design
> ![Screenshot 2022-10-05 183440](https://user-images.githubusercontent.com/81727988/194064427-a959b018-4114-4866-a84e-bdad20767446.png)
> 
> ### Fimga design
> ![figa](https://user-images.githubusercontent.com/81727988/194064486-5a78248a-2efa-4266-b21a-8548aec7b328.png)

- [ ] This required changes has not been implemented. Kindly give it attention and make it look like the guiding figma template

2022-10-06 01:01 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

-  No linter errors. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 
-   Good README file. :heavy_check_mark: 

![](https://user-images.githubusercontent.com/20554583/192241479-b6304cb0-f256-4c64-a258-4f5a40a1e960.gif)


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-06 07:28 UTC, mckent05 approved these changes
Hi @obed300,

# STATUS: APPROVED ✔️ ✔️  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well-done! 🎉 

## Highlights
- Your repo looks professional 👏 
- Descriptive commit messages 👍 👍 

## Optional suggestions
- Please I'd suggest that you make sure your site is responsive. This will ensure that your portfolio fits properly across all screen sizes 🙏 🙏 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-08 19:22 UTC, merged